### ISSUE TITLE
Included libwolfssl does not compile with GCC 11.1.0 (latest devkitPPC)

### ISSUE THREAD

**Issue by eku** [Fledge68/WiiFlow_Lite#275]
I'm trying to compile WiiFlow Lite with the latest devkitPPC (official docker container) and GCC complains about libwolfssl:

```
In file included from /src/source/network/https.h:8,
                 from /src/source/booter/external_booter.cpp:36:
/src/source/libwolfssl/ssl.h:2360:64: error: reference to 'byte' is ambiguous
 2360 | WOLFSSL_API int   wolfSSL_DTLS_SetCookieSecret(WOLFSSL*, const byte*, word32);
      |                                                                ^~~~
```
~~Looks like they fixed it in July with 4.8.0. Current version is 4.8.1.~~

~~Any chance to update libwolfssl in this project?~~

`libwolfssl` within `usb_loader_gx` compiles fine.

**Comment by Fledge68** [comment]
fixed in this commit - https://github.com/Fledge68/WiiFlow_Lite/commit/12d21fa0a7362fefd84313815e6af7ec32415b26

**Comment by eku** [comment]
Great. Thanks.
